package com.shinhoandroid.test0909.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.shinhoandroid.test0909.bean.StudentAndTeacherBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STUDENT_AND_TEACHER_BEAN".
*/
public class StudentAndTeacherBeanDao extends AbstractDao<StudentAndTeacherBean, Void> {

    public static final String TABLENAME = "STUDENT_AND_TEACHER_BEAN";

    /**
     * Properties of entity StudentAndTeacherBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property StudentNo = new Property(0, Long.class, "studentNo", false, "STUDENT_NO");
        public final static Property TeacherId = new Property(1, Long.class, "teacherId", false, "TEACHER_ID");
    }


    public StudentAndTeacherBeanDao(DaoConfig config) {
        super(config);
    }
    
    public StudentAndTeacherBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STUDENT_AND_TEACHER_BEAN\" (" + //
                "\"STUDENT_NO\" INTEGER," + // 0: studentNo
                "\"TEACHER_ID\" INTEGER);"); // 1: teacherId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STUDENT_AND_TEACHER_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StudentAndTeacherBean entity) {
        stmt.clearBindings();
 
        Long studentNo = entity.getStudentNo();
        if (studentNo != null) {
            stmt.bindLong(1, studentNo);
        }
 
        Long teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindLong(2, teacherId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StudentAndTeacherBean entity) {
        stmt.clearBindings();
 
        Long studentNo = entity.getStudentNo();
        if (studentNo != null) {
            stmt.bindLong(1, studentNo);
        }
 
        Long teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindLong(2, teacherId);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public StudentAndTeacherBean readEntity(Cursor cursor, int offset) {
        StudentAndTeacherBean entity = new StudentAndTeacherBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // studentNo
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1) // teacherId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StudentAndTeacherBean entity, int offset) {
        entity.setStudentNo(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTeacherId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(StudentAndTeacherBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(StudentAndTeacherBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(StudentAndTeacherBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
